### ISSUE TITLE
Please remove this repository or make it private!

### ISSUE THREAD

**Issue by atzeus** [pelledrijver/IJVM-emulator#2]
Please remove this repository or make it private!

Whatever you removed is still accessible via the history. Note that the structure of the project is copyrighted, not just a few lines.

Please remove this repository or make it private!

Regards,

Atze

**Comment by atzeus** [comment]
The exam commission has decided that supplying code to other students is also fraud. Take this down, you will be PROSECUTED if someone hands in this code!

**Comment by pelledrijver** [comment]
Dear Atze,

I will make the repository private 2 weeks before period 6 starts to prevent students from finding this solution. I do this for all my code written in university courses and several TAs I've spoken to agree that this is the best way to handle this problem.

**Comment by atzeus** [comment]
Hi Pelle,

Sorry, could you please just make it private altogether? The exam commission has decided that posting solutions on GitHub is also fraud, and you do not own the copyright on the framework. Thanks!

Regards,
Atze
